---
- hosts: mywebservers
  become: yes
  vars:
    myvar1: kasi
    myvar2: cool
    tasks:
    - name: Display the var values
      debug:
        msg: "{{ cmpname }}"
    - name: Display the val1
      debug: 
        msg: "{{ myval1 }}"    