---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on Redhat(apache2)
    yum:
      name: httpd
      state: present
  - name: start apache2 service
    service:
      name: httpd
      state: started    
